config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/friends'

  get 'users/requests'

  resources :posts do
      resources :comments
  end

  devise_for :users 
  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index'
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end
  get 'pages/index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts
  has_many :friendships
  has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"

  has_many :active_friends, -> { where(friendships: { approved: true}) }, :through => :friendships, :source => :friend
  has_many :passive_friends, -> { where(friendships: { approved: true}) }, :through => :passive_friendships, :source => :user
  has_many :pending_friends, -> { where(friendships: { approved: false}) }, :through => :friendships, :source => :friend
  has_many :requested_friendships, -> { where(friendships: { approved: false}) }, :through => :passive_friendships, :source => :user

  def friends
      active_friends | passive_friends
  end

  def to_s
    username
  end
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  has_many :comments, dependent: :destroy

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
	  @users = User.all
	end

	def show
	  @user = current_user
	end

	def new
	  @user = User.new
	end

	def friends
		@user = current_user
	end

	def requests
		@user = current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/friends.html.erb
<div class="yeild">
<h2>Friends</h2><hr>

        <% @user.friends.each do |friend| %><br>
          <div class="thumb"><%= image_tag(friend.avatar.url(:thumb)) %></div>
          <div><strong><%= friend.username %></strong></div> 
          <% if current_user == @user %>
          <div><%= link_to "Remove friend", friendship_path(:id => friend), :method => :delete %></div>
          <% end %>
      <% end %>
</div>

app/views/users/index.html.erb
<div class="yeild">
	<h2>Find Friends</h2><hr>
		<% @users.each do |user| %><br>
			<div class="friend-list">
				<% if user.username != current_user.username %>
					<div class="thumb"><%= image_tag(user.avatar.url(:thumb)) %></div>
					<div><strong><%=h user.username %></strong></div>
					<div><%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %></div>
				<% end %>
			</div>
		<% end %>

	<br><hr><br><br>

	<div class="notice"><%= notice %></div>
	<div class="alert"><%= alert %></div>

</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/requests.html.erb
<div class="yeild">
	
    <% if current_user == @user %>
        <h2>Friend Requests</h2><hr>

            <% @user.requested_friendships.each do |request| %><br>
              <div class="thumb"><%= image_tag(request.avatar.url(:thumb)) %></div>
              <%= request.username %> 
              <div><%= link_to "Accept", friendship_path(:id => request), :method => "put" %> 
              <%= link_to "Ignore", friendship_path(:id => request), :method => :delete %></div>
          <% end %>

    <% end %>
</div>

app/views/users/show.html.erb
<div class="yeild">
	<div class="thumb"><%= image_tag(current_user.avatar.url(:thumb)) %></div>
	<div><strong><%= @user.username %></strong></div>
	<div>
		<%= link_to "Edit Profile", edit_user_registration_path %></div>
	<div>
		<p>I am <%= @user.username %> and it is about me. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p>
	</div>

	<hr>
	
	<div>
	  | <%= link_to "Find Friends", users_index_path %> |
		<%= link_to "Friends", users_friends_path %> (<%= @user.friends.count %>) |
		<%= link_to "Friend Requests", users_requests_path %>  (<%= @user.requested_friendships.count %>) |
	</div>
	
	<div class="notice">
		<p>
			<%= notice %>
		</p>
	</div>
	<div class="alert">
		<p>
			<%= alert %>
		</p>
	</div>

	

</div>